# -*- coding: utf-8 -*-
"""Credit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B210cji5DpzX2w5SJCoxodLuUgnNLbly
"""

# Install
!pip install scikit-learn pandas -q

# Import
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Create Data
df = pd.DataFrame({
    'income':          [50000,30000,80000,20000,60000,15000,90000,40000,
                        70000,25000,95000,35000,45000,55000,65000,75000],
    'debts':           [10000,25000, 5000,18000,12000,14000, 3000,20000,
                         8000,22000, 2000,16000,11000,13000, 7000, 9000],
    'payment_history': [1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1],
    'creditworthy':    [1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1]
})

print("✅ Data loaded!")
print(df)

# Prepare
X = df[['income','debts','payment_history']]
y = df['creditworthy']

# Split
X_train,X_test,y_train,y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"\n✅ Train: {len(X_train)} rows | Test: {len(X_test)} rows")

# Train
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
print("✅ Model trained!")

# Predict & Results
y_pred = model.predict(X_test)
print("\n📊 RESULTS:")
print(classification_report(y_test, y_pred))

# Try prediction
print("🔮 Custom Prediction:")
my_customer = [[45000, 8000, 1]]  # income, debts, payment_history
result = model.predict(my_customer)
print("Give loan?" , "YES" if result[0]==1 else "NO")